## ArO (c)2024 for ArchLinux
alias ll='ls -lh'
alias la='ls -lha'
alias l='ls -CF'
alias em='emacs -nw'
alias dd='dd status=progress'
alias _='sudo'
alias _i='sudo -i'
alias hack='echo "HACK Linux ArO(c)2024" | figlet'
#
alias df='df -h'
alias free='free -mt'
# alias pp='PATH=/home/$USER/sh:$PATH'
alias c='clear && echo "NovaOS  (c)2024" | figlet'
alias i='ip -c a'
# alias s='cd /home/$USER/sh'; ls     # cool effect
alias s='cd /home/$USER/sh'
alias b='cd /home/as/.local/bin'
# alias akring='sudo pacman -Sy archlinux-keyring --noconfirm'
alias breload='cd ~ && source ~/.bashrc'
alias clrcache='sudo pacman -Scc'
# alias hack='echo "HACK  Linux  ArO(c)2021" | figlet'
# alias aro='echo "https://aro.5v.pl" | toilet -w 130; beep'
# alias os='echo "ParrotOS Security" | toilet -w 130; beep'
# alias pass='echo "root lock but $USER pass - 3x1..2x7"'
#
alias gpg-check='gpg2 --keyserver-options auto-key-retrieve --verify'
alias gpg-retrieve='gpg2 --keyserver-options auto-key-retrieve --receive-keys'
alias grubup='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias home='cd ~'
alias hw='hwinfo --short'
alias info='sudo pacman -Si '
alias infox='sudo pacman -Sii '
alias install='sudo pacman -S'
alias iso='cat /etc/dev-rel | awk -F '\''='\'' '\''/ISO/ {print }'\'''
alias jctl='journalctl -p 3 -xb'
alias l='eza -lah --color=always --group-directories-first --icons'
alias lt='eza -aT --color=always --group-directories-first --icons'
# alias man='batman '
alias matrix='cmatrix -s -C cyan'
alias mirrorx='sudo reflector --age 6 --latest 20  --fastest 20 --threads 5 --sort rate --protocol https --save /etc/pacman.d/mirrorlist'
alias mirrorxx='sudo reflector --age 6 --latest 20  --fastest 20 --threads 20 --sort rate --protocol https --save /etc/pacman.d/mirrorlist'
alias mkfile='touch'
alias mkpkg='sudo nano /etc/makepkg.conf'
alias nbashrc='sudo nano ~/.bashrc'
alias ngrub='sudo nano /etc/default/grub'
alias nlightdm='sudo $EDITOR /etc/lightdm/lightdm.conf'
alias nmirrorlist='sudo nano /etc/pacman.d/mirrorlist'
alias nsddm='sudo nano /etc/sddm.conf'
alias orphans='sudo pacman -Rns $(pacman -Qtdq)'
alias paruskip='paru -S --mflags --skipinteg'
alias pconf='sudo nano /etc/pacman.conf'
alias pget='paru -S '
alias pingme='ping -c64 github.com'
alias prem='paru -R '
alias probe='sudo -E hw-probe -all -upload'
alias remove='sudo pacman -R'
alias rip='expac --timefmt='\''%Y-%m-%d %T'\'' '\''%l\t%n %v'\'' | sort | tail -200 | nl'
alias riplong='expac --timefmt='\''%Y-%m-%d %T'\'' '\''%l\t%n %v'\'' | sort | tail -3000 | nl'
alias rkeys='sudo pacman-key --refresh-keys'
alias search='sudo pacman -Qs'
alias traceme='traceroute github.com'
alias unlock='sudo rm /var/lib/pacman/db.lck'
alias upall='topgrade'
alias update='sudo pacman -Syyu'
alias userlist='cut -d: -f1 /etc/passwd'
alias wget='wget -c'
alias yayskip='yay -S --mflags --skipinteg'
alias yget='yay -S '
alias yrem='yay -R '
alias yta-best='yt-dlp --extract-audio --audio-format best '
alias ytv-best='yt-dlp -f '\''bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio'\'' --merge-output-format mp4 '
# alias qm='qmenu model.mnu'
# -= ArO=- for Manjaro (c)2024.11.01

